import React from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface CaptionResult {
  timeLabel: string;
  caption: string;
  importance: number;
}

interface ExportButtonProps {
  videoName: string;
  captions: CaptionResult[];
  summary: string;
  keyEvents: string[];
  alertLevel: string;
  translatedCaptions?: { timeLabel: string; caption: string }[] | null;
  translatedSummary?: string | null;
}

function buildTextContent(props: ExportButtonProps): string {
  const lines: string[] = [];
  lines.push("═══════════════════════════════════════════");
  lines.push("  HAVCM — Video Captioning Report");
  lines.push("═══════════════════════════════════════════");
  lines.push("");
  lines.push(`Video: ${props.videoName}`);
  lines.push(`Date: ${new Date().toLocaleString()}`);
  lines.push(`Alert Level: ${props.alertLevel.toUpperCase()}`);
  lines.push("");
  lines.push("───────────────────────────────────────────");
  lines.push("  FRAME-LEVEL CAPTIONS");
  lines.push("───────────────────────────────────────────");
  lines.push("");

  for (const cap of props.captions) {
    lines.push(`[${cap.timeLabel}]  (Attention: ${(cap.importance * 100).toFixed(0)}%)`);
    lines.push(`  ${cap.caption}`);
    lines.push("");
  }

  lines.push("───────────────────────────────────────────");
  lines.push("  VIDEO SUMMARY");
  lines.push("───────────────────────────────────────────");
  lines.push("");
  lines.push(props.summary);
  lines.push("");

  if (props.keyEvents.length > 0) {
    lines.push("KEY EVENTS:");
    for (const event of props.keyEvents) {
      lines.push(`  ▸ ${event}`);
    }
    lines.push("");
  }

  if (props.translatedCaptions && props.translatedSummary) {
    lines.push("───────────────────────────────────────────");
    lines.push("  TRANSLATED CAPTIONS");
    lines.push("───────────────────────────────────────────");
    lines.push("");
    for (const cap of props.translatedCaptions) {
      lines.push(`[${cap.timeLabel}]  ${cap.caption}`);
    }
    lines.push("");
    lines.push("TRANSLATED SUMMARY:");
    lines.push(props.translatedSummary);
    lines.push("");
  }

  lines.push("═══════════════════════════════════════════");
  lines.push("  Generated by HAVCM");
  lines.push("═══════════════════════════════════════════");

  return lines.join("\n");
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const ExportButton: React.FC<ExportButtonProps> = (props) => {
  const baseName = props.videoName.replace(/\.[^.]+$/, "") || "video";

  const handleTextExport = () => {
    const content = buildTextContent(props);
    downloadFile(content, `${baseName}_captions.txt`, "text/plain");
  };

  const handleCsvExport = () => {
    const lines = ["Timestamp,Caption,Attention Weight"];
    for (const cap of props.captions) {
      const escaped = cap.caption.replace(/"/g, '""');
      lines.push(`"${cap.timeLabel}","${escaped}","${(cap.importance * 100).toFixed(0)}%"`);
    }
    downloadFile(lines.join("\n"), `${baseName}_captions.csv`, "text/csv");
  };

  const handleJsonExport = () => {
    const data = {
      videoName: props.videoName,
      generatedAt: new Date().toISOString(),
      alertLevel: props.alertLevel,
      captions: props.captions,
      summary: props.summary,
      keyEvents: props.keyEvents,
      ...(props.translatedCaptions && {
        translatedCaptions: props.translatedCaptions,
        translatedSummary: props.translatedSummary,
      }),
    };
    downloadFile(JSON.stringify(data, null, 2), `${baseName}_captions.json`, "application/json");
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="cyber" size="sm" className="gap-2">
          <Download className="w-4 h-4" />
          Export Report
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleTextExport}>
          📄 Download as Text (.txt)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleCsvExport}>
          📊 Download as CSV (.csv)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleJsonExport}>
          🔧 Download as JSON (.json)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportButton;
